DROP TABLE RESTAURANT_FOOD;
DROP TABLE FOOD;
DROP TABLE FOOD_TYPE;
DROP TABLE RESERVATION_PLACES;
DROP TABLE RESTAURANT_TABLE;
DROP TABLE RESTAURANT_REASON;
DROP TABLE RESTAURANT;
DROP TABLE COUNTY;
DROP TABLE REASON;
DROP TABLE RESERVATION;

DROP DATABASE REMAN;

DROP USER 'REMAN_DEVELOPER'@'localhost';
